<?php

// Translation of file /home/dennis/www/coscms/modules/blog_simple/views/index.inc

$_COS_LANG_MODULE['blog_simple_edit_entry'] = 'Edit Entry';
$_COS_LANG_MODULE['blog_simple_delete_entry'] = 'Delete Entry';

// Translation of file /home/dennis/www/coscms/modules/blog_simple/model.blog_simple.inc

$_COS_LANG_MODULE['blog_simple_content'] = 'Content';
$_COS_LANG_MODULE['blog_simple_delete_entry'] = 'Delete Entry';
$_COS_LANG_MODULE['blog_simple_add_title'] = 'Title';
$_COS_LANG_MODULE['blog_simple_entry_created'] = 'Entry Created';
$_COS_LANG_MODULE['blog_simple_view_all'] = 'View List';
$_COS_LANG_MODULE['blog_simple_view_entry'] = 'View Entry';
$_COS_LANG_MODULE['blog_simple_update_entry'] = 'Update Entry';
$_COS_LANG_MODULE['blog_simple_entry_updated'] = 'Entry Updated';
$_COS_LANG_MODULE['blog_simple_delete_entry'] = 'Delete Entry';
$_COS_LANG_MODULE['blog_simple_entry_deleted'] = 'Entry Deleted';


$_COS_LANG_MODULE['blog_simple_written_by'] = 'Written By';
$_COS_LANG_MODULE['blog_simple_last_updated'] = 'Last Updated';


$_COS_LANG_MODULE['blog_simple_no_title'] = 'No title';
$_COS_LANG_MODULE['blog_simple_no_content'] = 'No content';


