<?php


// Translation of file /modules/blog_simple/views.php

$_COS_LANG_MODULE['blog_simple_edit_entry'] = 'Edit Entry';
$_COS_LANG_MODULE['blog_simple_delete_entry'] = 'Delete Entry';

// Translation of file /modules/blog_simple/module.php

$_COS_LANG_MODULE['blog_simple_add_entry'] = 'Add Entry';
$_COS_LANG_MODULE['blog_simple_title'] = 'My Blog';
$_COS_LANG_MODULE['blog_simple_no_title'] = 'No Title';
$_COS_LANG_MODULE['blog_simple_no_entry'] = 'No entry';
$_COS_LANG_MODULE['blog_simple_view_all'] = 'View All';
$_COS_LANG_MODULE['blog_simple_view_entry'] = 'View Entry';
$_COS_LANG_MODULE['blog_simple_add_title'] = 'Add Entry';
$_COS_LANG_MODULE['blog_simple_entry_created'] = 'Entry Created';
$_COS_LANG_MODULE['blog_simple_update_entry'] = 'Update Entry';
$_COS_LANG_MODULE['blog_simple_entry_updated'] = 'Entry Updated';
$_COS_LANG_MODULE['blog_simple_entry_deleted'] = 'Entry Deleted';
