<?php

// Translation of file /modules/blog_simple/views.php

$_COS_LANG_MODULE['Edit'] = 'Edit';
$_COS_LANG_MODULE['Delete'] = 'Delete';
// Translation of file /modules/blog_simple/module.php

$_COS_LANG_MODULE['Delete entry'] = 'Delete entry';
$_COS_LANG_MODULE['Edit entry'] = 'Edit entry';
$_COS_LANG_MODULE['Add entry'] = 'Add entry';
$_COS_LANG_MODULE['Title'] = 'Title';
$_COS_LANG_MODULE['Entry'] = 'Entry';
$_COS_LANG_MODULE['Submit'] = 'Submit';
$_COS_LANG_MODULE['No title'] = 'No title';
$_COS_LANG_MODULE['No entry'] = 'No entry';
$_COS_LANG_MODULE['View all blog entries'] = 'View all blog entries';
$_COS_LANG_MODULE['View entry'] = 'View entry';
$_COS_LANG_MODULE['Entry created'] = 'Entry created';
$_COS_LANG_MODULE['Update entry'] = 'Update entry';
$_COS_LANG_MODULE['Entry updated'] = 'Entry updated';
$_COS_LANG_MODULE['Entry deleted'] = 'Entry deleted';
