<?php

// Translation of file /home/dennis/www/coscms/modules/blog_simple/views/view.inc

$_COS_LANG_MODULE['blog_simple_written_by'] = 'blog_simple_written_by';
$_COS_LANG_MODULE['blog_simple_edit_entry'] = 'blog_simple_edit_entry';
$_COS_LANG_MODULE['blog_simple_delete_entry'] = 'blog_simple_delete_entry';
// Translation of file /home/dennis/www/coscms/modules/blog_simple/views/index.inc

// Translation of file /home/dennis/www/coscms/modules/blog_simple/model.blog_simple.inc

$_COS_LANG_MODULE['blog_simple_title'] = 'blog_simple_title';
$_COS_LANG_MODULE['blog_simple_entry'] = 'blog_simple_entry';
$_COS_LANG_MODULE['blog_simple_add_entry'] = 'blog_simple_add_entry';
$_COS_LANG_MODULE['blog_simple_no_title'] = 'blog_simple_no_title';
$_COS_LANG_MODULE['blog_simple_no_entry'] = 'blog_simple_no_entry';
$_COS_LANG_MODULE['blog_simple_add_title'] = 'blog_simple_add_title';
$_COS_LANG_MODULE['blog_simple_entry_created'] = 'blog_simple_entry_created';
$_COS_LANG_MODULE['blog_simple_view_all'] = 'blog_simple_view_all';
$_COS_LANG_MODULE['blog_simple_view_entry'] = 'blog_simple_view_entry';
$_COS_LANG_MODULE['blog_simple_update_entry'] = 'blog_simple_update_entry';
$_COS_LANG_MODULE['blog_simple_entry_updated'] = 'blog_simple_entry_updated';
$_COS_LANG_MODULE['blog_simple_entry_deleted'] = 'blog_simple_entry_deleted';
